#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=Test
#spring.datasource.password=Test
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          discord:
            clientName: Serex
            client-id: 961834104670810132
            client-secret: f1LnjDbDCtFPoHLRq5kRjb0tRy4Vr7dQ
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/discord"
            scope:
              - identify
              - email
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: username